{% macro get_type(type) %}{% if type is defined %}{{ type }}{% else %}fmnist{% endif %}{% endmacro %}
{% macro get_aggregation_methods(aggregation_methods) %}{% if aggregation_methods is defined %}{{ aggregation_methods }}{% else %}our_aggr{% endif %}{% endmacro %}
{% macro get_attack_methods(attack_methods) %}{% if attack_methods is defined %}{{ attack_methods }}{% else %}targeted_label_flip{% endif %}{% endmacro %}
{% macro get_noniid(noniid) %}{% if noniid is defined %}{{ noniid }}{% else %}iid{% endif %}{% endmacro %}

gpu: {{ gpu|default('0') }}
type: {{ type|default('cifar') }}
test_batch_size: 64
{% if get_type(type) != 'loan' %}
lr: 0.1
{% else %}
lr: 0.001
{% endif %}
momentum: 0.9
decay: 0.0005
batch_size: 64
# if type is cifar epoch is 300, else epoch is 150
{% if get_type(type) in ['cifar'] %}
epochs: {{ epochs|default(210) }}
{% elif get_type(type) == 'loan' %}
epochs: {{ epochs|default(300) }}
{% else %}
epochs: {{ epochs|default(50) }}
{% endif %}
{% if get_type(type) != 'cifar' %}
internal_epochs: 1
{% else %}
internal_epochs: 2
{% endif %}
aggr_epoch_interval: 1
eta: {{ eta|default(0.1) }}

{% if get_type(type) == 'loan' %}
no_models: 14
{% elif get_aggregation_methods(aggregation_methods) == 'our_aggr' and injective_florida is defined%}
no_models: {{ no_models|default(25) }}
{% else %}
no_models: {{ no_models|default(100) }}
{% endif %}
{% if get_type(type) == 'loan' %}
{% set number_of_total_participants = 51 %}
{% else %}
{% set number_of_total_participants = 100 %}
{% endif %}
number_of_total_participants: {{ number_of_total_participants }}
is_random_namelist: true
is_random_adversary: true




# aggregation_methods Allowed values are: [ 'mean', 'geom_median','flame', 'our_aggr', 'afa', 'foolsgold']
aggregation_methods: {{ get_aggregation_methods(aggregation_methods) }}

{% if get_aggregation_methods(aggregation_methods) == 'mean' %}
oracle_mode: {{ oracle_mode|default('false') }}
{% endif %}

{% if get_aggregation_methods(aggregation_methods) == 'flame' %}
{% endif %}

{% if get_aggregation_methods(aggregation_methods) == 'geom_median' %}
geom_median_maxiter: 10
{% endif %}

{% if get_aggregation_methods(aggregation_methods) == 'foolsgold' %}
fg_use_memory: true
{% endif %}

{% if get_aggregation_methods(aggregation_methods) == 'afa' %}
afa_alpha_0: 3
afa_beta_0: 3
afa_epsilon: 2
afa_del_epsilon: 0.5
{% endif %}

{% if get_aggregation_methods(aggregation_methods) == 'our_aggr' %}
injective_florida: {{ injective_florida|default('false') }}
contrib_adjustment: {{ contrib_adjustment|default(0.75) }}
validation_metric_options:
  - LIPC
  - loss_impact_only
  - accuracy
validation_metric: {{ validation_metric|default('LIPC') }}
no_ensemble: false
{% endif %}



is_poison: {{ is_poison|default('true') }}
{% if get_type(type) == 'cifar' %}
internal_poison_epochs: 2
{% elif get_type(type) == 'loan' %}
internal_poison_epochs: 2
{% else %}
internal_poison_epochs: 3
{% endif %}
poisoning_per_batch: {{ poisoning_per_batch|default(10) }}
{% if get_type(type) != 'loan' %}
poison_lr: 0.05
{% else %}
poison_lr: 0.0005
{% endif %}
poison_step_lr: true
poison_decay: 0.005
{% if get_type(type) != 'cifar' %}
poison_momentum: 0.7
{% else %}
poison_momentum: 0.9
{% endif %}
results_json: true
alpha_loss: 1
{% if get_type(type) == 'loan' %}
s_norm: 1000000
{% endif %}

attack_methods_options:
  - 'targeted_label_flip'
  - 'dba'
  - 'server_imitation_attack'
  - 'inner_product_manipulation'
  - 'attack_of_the_tails'
  - 'semantic_attack'
attack_methods: {{ get_attack_methods(attack_methods) }}

mal_val_type_options:
  - None
  - naive
  - adaptive
mal_val_type: {% if mal_val_type is defined %}{{ mal_val_type }}{% else %}'None'{% endif %}
{% if get_attack_methods(attack_methods) == 'targeted_label_flip' %}
tlf_label_options:
  - easy
  - medium
  - hard
tlf_label: {% if tlf_label is defined %}{{ tlf_label }}{% else %}'easy'{% endif %}
src_grp_mal: 3
{% endif %}

{% if get_attack_methods(attack_methods) == 'dba' %}
poison_label_swap: {% if get_type(type) == 'loan' %}7{% else %}2{% endif %}
centralized_test_trigger: False
trigger_num: {% if get_type(type) == 'loan' %}3{% else %}4{% endif %}
{% if get_type(type) in ['fmnist', 'emnist'] %}
0_poison_pattern: [[0, 0], [0, 1], [0, 2], [0, 3]]
1_poison_pattern: [[0, 6], [0, 7], [0, 8], [0, 9]]
2_poison_pattern: [[3, 0], [3, 1], [3, 2], [3, 3]]
3_poison_pattern: [[3, 6], [3, 7], [3, 8], [3, 9]]
{% elif get_type(type) == 'cifar' %}
0_poison_pattern: [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
1_poison_pattern: [[0, 9], [0, 10], [0, 11], [0, 12], [0, 13], [0, 14]]
2_poison_pattern: [[4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5]]
3_poison_pattern: [[4, 9], [4, 10], [4, 11], [4, 12], [4, 13]]
{% elif get_type(type) == 'loan' %}
0_poison_trigger_names: ['num_tl_120dpd_2m', 'num_tl_90g_dpd_24m']
1_poison_trigger_names: ['pub_rec_bankruptcies', 'pub_rec']
2_poison_trigger_names: ['acc_now_delinq', 'tax_liens']
0_poison_trigger_values: [10, 80]
1_poison_trigger_values: [20, 100]
2_poison_trigger_values: [20, 100]
{% endif %}
{% endif %}

{% if get_attack_methods(attack_methods) == 'attack_of_the_tails' %}
edge_split: {{ edge_split|default(0.1) }}
{% endif %}

{% set mal_participant_frac = mal_pcnt | float if mal_pcnt is defined else 0.4 %}
{% set number_of_adversary = mal_participant_frac * number_of_total_participants %}
number_of_adversary_{{ get_attack_methods(attack_methods) }}: {{ number_of_adversary|round|int if number_of_adversary % 1 > 0 else number_of_adversary|int }}
{% if get_type(type) == 'loan' %}
adversary_list: [FL, IL, NJ, PA, OH, GA, VA, NC, MI, MD, AZ, CT, MO, TN]
{% endif %}
save_data: 1




{% if get_noniid(noniid) == 'one_class_expert' %}
bias: 0.5
noniid: true
{% else %}
noniid: false
{% if get_noniid(noniid) == 'sampling_dirichlet' %}
sampling_dirichlet: true
dirichlet_alpha: 0.9
{% endif %}
{% endif %}

baseline: true


camera_ready: false


save_model: false
{% if get_type(type) != 'cifar' %}
save_on_epochs: [10, 15, 20, 25, 30, 35]
{% else %}
save_on_epochs: [50, 100, 150, 200]
{% endif %}

resumed_model: {{ resumed_model|default('true') }}
{% if get_type(type) == 'fmnist' %}
resumed_model_name: utils/model_bank/fmnist/model_last.pt.tar.epoch_35
{% elif get_type(type) == 'cifar' %}
resumed_model_name: utils/model_bank/cifar/model_last.pt.tar.epoch_200
{% elif get_type(type) == 'emnist' %}
resumed_model_name: utils/model_bank/emnist/model_last.pt.tar.epoch_35
{% elif get_type(type) == 'celebA' %}
resumed_model_name: utils/model_bank/celebA/model_last.pt.tar.epoch_200
{% elif get_type(type) == 'loan' %}
resumed_model_name: utils/model_bank/loan/model_last.pt.tar.epoch_200
{% endif %}
resumed_model_path: utils/model_bank/{{ get_type(type) }}

minimize_logging: true
speed_boost: true
vis_train: false
vis_train_batch_loss: false
vis_trigger_split_test: false
track_distance: false
batch_track_distance: false
log_interval: 2


diff_privacy: false
{% if get_type(type) in ['cifar', 'loan'] %}
sigma: 0.01
{% else %}
sigma: 0.001
{% endif %}


poison_epochs: [{% for i in range(1, 301) %}{{ i }}, {% endfor %}]
# poison_epochs: [70]